### ISSUE TITLE
Assert selects wrong opcode depending on label position

### ISSUE THREAD

**Issue by Henry00IS** [hlorenzi/customasm#14] opened 2019-06-26 13:04 UTC
```asm

#cpudef
{
	jmp {address} -> { assert(address <=   0xFF), 0x01 @ address[7:0]  }
	jmp {address} -> { assert(address <= 0xFFFF), 0x02 @ address[15:0] }
}
```

---

```asm
bla:
jmp bla
```

Output: `01 00`

---

```asm
jmp bla
bla:
```

Output: `02 00 03`

---

This does work fine if you pass in a number like 0xAB or 0xBEEF. Apparently this issue happens throughout the program, anything above the current instruction gets the short version, anything below it gets the long version.

I love this program by the way, thank you so much for making it! :grin:

**Comment by hlorenzi** [comment] 2019-06-26 17:38
Thank you, I'm very glad you like the program!

Your issue is unfortunately by design, though. The assembler is forced to select a match for every instruction sequentially. If you use any label which hasn't been defined previously, the assembler will ignore your asserts and always choose the last of your instruction definitions.

I believe this would be the case with most assemblers out there. If I end up introducing macros, functions, and whatnot, a fix for this would probably get very nasty!

**Closed** 2019-07-10 14:35 UTC
